using System.Diagnostics.CodeAnalysis;

// This file is used to store suppressions for code analysis warnings that should
// be applied project-wide. Generated by GitHub Copilot assistant per user request.

[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S2326", Justification = "TSource is intentionally unused to preserve generic API symmetry.")]
